#!/bin/bash

set -eo pipefail

PLEX_UID=${PLEX_UID:-1337}
PLEX_GID=${PLEX_GID:-1337}

groupadd -g $PLEX_GID plex
useradd -c "Plex Media Server" -g $PLEX_GID -u $PLEX_UID -d /var/lib/plexmediaserver plex
chown plex:plex /var/lib/plexmediaserver

tail -F "/var/lib/plexmediaserver/Library/Logs/Plex Media Server/Plex Media Server.log" 2>/dev/null &
export LD_LIBRARY_PATH=/usr/lib/plexmediaserver
exec gosu plex:plex "/usr/lib/plexmediaserver/Plex Media Server" "$@"
